# in order to DRY,we can use common config 
# common config
 common: &common
   adapter: mysql
   encoding: utf8
   pool: 10
   username: root
   password: '12345678'
   host: localhost
   port: 3306

# development config
 development:
   database: testpro
   <<: *common

# test config
 test:
   database: projectshow_test
   <<: *common

#production config    
 production:
   <<: *common
   database: projectshow
